"""Deterministic config-fix snippets for low-risk header/CORS findings.

These are intentionally NOT generated by an LLM — a wrong header line is worse
than no snippet. Only the explicitly whitelisted finding types below produce
copy-pasteable Nginx / Apache / Express snippets.
"""

from __future__ import annotations

from typing import Any

# Finding types where the fix is a known, deterministic config change.
DETERMINISTIC_FIX_TYPES: frozenset[str] = frozenset(
    {
        "missing-csp",
        "missing-x-frame-options",
        "weak-hsts",
        "weak-hsts-max-age",
        "missing-x-content-type-options",
        "missing-referrer-policy",
        "cors-wildcard",
    }
)

# Canonical type used for templates (aliases map here).
_TYPE_ALIASES: dict[str, str] = {
    "weak-hsts-max-age": "weak-hsts",
}

_HEADER_LINES: dict[str, str] = {
    "missing-csp": "Content-Security-Policy \"default-src 'self'; frame-ancestors 'none'; base-uri 'self'; object-src 'none'\"",
    "missing-x-frame-options": "X-Frame-Options \"DENY\"",
    "weak-hsts": "Strict-Transport-Security \"max-age=63072000; includeSubDomains; preload\"",
    "missing-x-content-type-options": "X-Content-Type-Options \"nosniff\"",
    "missing-referrer-policy": "Referrer-Policy \"strict-origin-when-cross-origin\"",
}

_APACHE_HEADER_LINES: dict[str, str] = {
    "missing-csp": "Header always set Content-Security-Policy \"default-src 'self'; frame-ancestors 'none'; base-uri 'self'; object-src 'none'\"",
    "missing-x-frame-options": "Header always set X-Frame-Options \"DENY\"",
    "weak-hsts": "Header always set Strict-Transport-Security \"max-age=63072000; includeSubDomains; preload\"",
    "missing-x-content-type-options": "Header always set X-Content-Type-Options \"nosniff\"",
    "missing-referrer-policy": "Header always set Referrer-Policy \"strict-origin-when-cross-origin\"",
}

_EXPRESS_HEADERS: dict[str, str] = {
    "missing-csp": "res.setHeader(\"Content-Security-Policy\", \"default-src 'self'; frame-ancestors 'none'; base-uri 'self'; object-src 'none'\");",
    "missing-x-frame-options": "res.setHeader(\"X-Frame-Options\", \"DENY\");",
    "weak-hsts": "res.setHeader(\"Strict-Transport-Security\", \"max-age=63072000; includeSubDomains; preload\");",
    "missing-x-content-type-options": "res.setHeader(\"X-Content-Type-Options\", \"nosniff\");",
    "missing-referrer-policy": "res.setHeader(\"Referrer-Policy\", \"strict-origin-when-cross-origin\");",
}


def canonicalize_fix_type(finding_type: str) -> str | None:
    """Return the canonical whitelisted type, or None if not deterministic."""
    normalized = str(finding_type or "").strip().lower()
    if normalized not in DETERMINISTIC_FIX_TYPES:
        return None
    return _TYPE_ALIASES.get(normalized, normalized)


def is_deterministic_fix_type(finding_type: str) -> bool:
    return canonicalize_fix_type(finding_type) is not None


def _nginx_block(canonical: str) -> str:
    if canonical == "cors-wildcard":
        return (
            "# Replace Access-Control-Allow-Origin * with an explicit allowlist.\n"
            "# Example (adjust the origin):\n"
            "add_header Access-Control-Allow-Origin \"https://app.example.com\" always;\n"
            "# Do NOT set Access-Control-Allow-Credentials on public wildcard CORS."
        )
    line = _HEADER_LINES[canonical]
    # add_header name value;
    name, _, value = line.partition(" ")
    return f"add_header {name} {value} always;"


def _apache_block(canonical: str) -> str:
    if canonical == "cors-wildcard":
        return (
            "# Replace wildcard CORS with an explicit origin allowlist.\n"
            "Header always set Access-Control-Allow-Origin \"https://app.example.com\"\n"
            "# Do NOT combine wildcard ACAO with Access-Control-Allow-Credentials On"
        )
    return _APACHE_HEADER_LINES[canonical]


def _express_block(canonical: str) -> str:
    if canonical == "cors-wildcard":
        return (
            "// Replace cors({ origin: '*' }) with an explicit allowlist.\n"
            "app.use((req, res, next) => {\n"
            "  const allowed = new Set([\"https://app.example.com\"]);\n"
            "  const origin = req.headers.origin;\n"
            "  if (origin && allowed.has(origin)) {\n"
            "    res.setHeader(\"Access-Control-Allow-Origin\", origin);\n"
            "    res.setHeader(\"Vary\", \"Origin\");\n"
            "  }\n"
            "  // Do not set Access-Control-Allow-Credentials with a wildcard.\n"
            "  next();\n"
            "});"
        )
    header_line = _EXPRESS_HEADERS[canonical]
    return (
        "app.use((req, res, next) => {\n"
        f"  {header_line}\n"
        "  next();\n"
        "});"
    )


def generate_config_snippets_for_type(finding_type: str) -> dict[str, str] | None:
    """Return {nginx, apache, express} snippets, or None if type is not whitelisted."""
    canonical = canonicalize_fix_type(finding_type)
    if canonical is None:
        return None
    return {
        "nginx": _nginx_block(canonical),
        "apache": _apache_block(canonical),
        "express": _express_block(canonical),
        "finding_type": canonical,
    }


def generate_config_fixes(findings: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Build deterministic config-fix blocks for whitelisted findings only.

    One entry per distinct finding type (first occurrence wins for metadata).
    Each entry references the finding ids of that type so reports can attach
    snippets inline next to the matching findings.
    """
    by_type: dict[str, dict[str, Any]] = {}
    for finding in findings:
        ftype = str(finding.get("type", ""))
        snippets = generate_config_snippets_for_type(ftype)
        if snippets is None:
            continue
        canonical = snippets["finding_type"]
        fid = str(finding.get("id") or "")
        if canonical not in by_type:
            by_type[canonical] = {
                "finding_type": canonical,
                "finding_ids": [],
                "snippets": {
                    "nginx": snippets["nginx"],
                    "apache": snippets["apache"],
                    "express": snippets["express"],
                },
                "source": "deterministic_template",
            }
        if fid and fid not in by_type[canonical]["finding_ids"]:
            by_type[canonical]["finding_ids"].append(fid)
    return list(by_type.values())
